Import Libraries

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

import joblib

import warnings
warnings.filterwarnings("ignore")

In [2]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\S_Gayathri\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 1.8 MB/s eta 0:00:21
   - -------------------------------------- 1.6/37.3 MB 2.8 MB/s eta 0:00:13
   -- ------------------------------------- 2.1/37.3 MB 2.9 MB/s eta 0:00:13
   -- ------------------------------------- 2.6/37.3 MB 2.8 MB/s eta 0:00:13
   --- ------------------------------------ 3.1/37.3 MB 2.6 MB/s eta 0:00:14
   --- ------------------------------------ 3.7/37.3 MB 2.5 MB/s eta 0:00:14
   ---- ----------------------------------- 4.2/37.3 MB 2.5 MB/s eta 0:00:14
   ---- ----------------------------------- 4.5/37.3 MB 2.5 MB/s eta 0:00:14
   ----- ---------------------------------- 5.0/37.3 MB 2.5 MB/s eta 0:00:13
   ----- ---------------------------------- 5.5/37.3 MB 2.5 MB/s eta 0:00:13
   ------ --------------------------------- 6.0/37.3 MB 2.5 MB/s eta 0:00:13
   ------- -------------------------------- 6.6/37.3 MB 2.5 MB/s eta 0:00:13
   ------- -------------------------------- 7.1/37.3 MB 2.5 MB/s eta 0:00:13
   -------- ------------------------------- 7.6/37.3 MB 2.5 MB/s eta 0:00:12
   -------- ------------------------------- 8.1/37.3 MB 2.5 MB/s eta 0:00:12
   --------- ------------------------------ 8.7/37.3 MB 2.5 MB/s eta 0:00:12
   --------- ------------------------------ 9.2/37.3 MB 2.5 MB/s eta 0:00:12
   ---------- ----------------------------- 9.7/37.3 MB 2.5 MB/s eta 0:00:12
   ---------- ----------------------------- 10.2/37.3 MB 2.5 MB/s eta 0:00:11
   ----------- ---------------------------- 10.7/37.3 MB 2.5 MB/s eta 0:00:11
   ------------ --------------------------- 11.3/37.3 MB 2.5 MB/s eta 0:00:11
   ------------ --------------------------- 12.1/37.3 MB 2.5 MB/s eta 0:00:11
   ------------- -------------------------- 12.6/37.3 MB 2.5 MB/s eta 0:00:10
   -------------- ------------------------- 13.1/37.3 MB 2.5 MB/s eta 0:00:10
   -------------- ------------------------- 13.4/37.3 MB 2.5 MB/s eta 0:00:10
   --------------- ------------------------ 14.2/37.3 MB 2.5 MB/s eta 0:00:10
   --------------- ------------------------ 14.7/37.3 MB 2.5 MB/s eta 0:00:09
   ---------------- ----------------------- 15.2/37.3 MB 2.5 MB/s eta 0:00:09
   ---------------- ----------------------- 15.7/37.3 MB 2.5 MB/s eta 0:00:09
   ----------------- ---------------------- 16.3/37.3 MB 2.5 MB/s eta 0:00:09
   ----------------- ---------------------- 16.8/37.3 MB 2.5 MB/s eta 0:00:09
   ------------------ --------------------- 17.3/37.3 MB 2.5 MB/s eta 0:00:08
   ------------------- -------------------- 17.8/37.3 MB 2.5 MB/s eta 0:00:08
   ------------------- -------------------- 18.1/37.3 MB 2.5 MB/s eta 0:00:08
   ------------------- -------------------- 18.6/37.3 MB 2.5 MB/s eta 0:00:08
   -------------------- ------------------- 19.1/37.3 MB 2.5 MB/s eta 0:00:08
   -------------------- ------------------- 19.4/37.3 MB 2.5 MB/s eta 0:00:08
   --------------------- ------------------ 19.9/37.3 MB 2.5 MB/s eta 0:00:08
   --------------------- ------------------ 20.4/37.3 MB 2.5 MB/s eta 0:00:07
   ---------------------- ----------------- 21.0/37.3 MB 2.5 MB/s eta 0:00:07
   ---------------------- ----------------- 21.2/37.3 MB 2.5 MB/s eta 0:00:07
   ----------------------- ---------------- 21.8/37.3 MB 2.5 MB/s eta 0:00:07
   ----------------------- ---------------- 22.3/37.3 MB 2.4 MB/s eta 0:00:07
   ------------------------ --------------- 22.8/37.3 MB 2.4 MB/s eta 0:00:06
   ------------------------- -------------- 23.3/37.3 MB 2.4 MB/s eta 0:00:06
   ------------------------- -------------- 23.9/37.3 MB 2.4 MB/s eta 0:00:06
   -------------------------- ------------- 24.4/37.3 MB 2.4 MB/s eta 0:00:06
   -------------------------- ------------- 24.9/37.3 MB 2.5 MB/s eta 0:00:06
   --------------------------- ------------ 25.4/37.3 MB 2.5 MB/s eta 0:00:05
   --------------------------- ------------ 26.0/37.3 MB 2.5 MB/s eta 0:00:05
   ---------------------------- ----------- 26.5/37.3 MB 2.5 MB/s eta 0:00:05
   ----------------------------- ---------- 27.3/37.3 MB 2.5 MB/s eta 0:00:05
   ----------------------------- ---------- 27.8/37.3 MB 2.5 MB/s eta 0:00:04
   ------------------------------ --------- 28.3/37.3 MB 2.5 MB/s eta 0:00:04
   ------------------------------ --------- 28.8/37.3 MB 2.5 MB/s eta 0:00:04
   ------------------------------- -------- 29.4/37.3 MB 2.5 MB/s eta 0:00:04
   ------------------------------- -------- 29.6/37.3 MB 2.5 MB/s eta 0:00:04
   -------------------------------- ------- 30.1/37.3 MB 2.5 MB/s eta 0:00:03
   -------------------------------- ------- 30.4/37.3 MB 2.4 MB/s eta 0:00:03
   --------------------------------- ------ 30.9/37.3 MB 2.4 MB/s eta 0:00:03
   --------------------------------- ------ 31.5/37.3 MB 2.4 MB/s eta 0:00:03
   ---------------------------------- ----- 31.7/37.3 MB 2.4 MB/s eta 0:00:03
   ---------------------------------- ----- 32.2/37.3 MB 2.4 MB/s eta 0:00:03
   ----------------------------------- ---- 32.8/37.3 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 33.0/37.3 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 33.6/37.3 MB 2.4 MB/s eta 0:00:02
   ------------------------------------ --- 34.1/37.3 MB 2.4 MB/s eta 0:00:02
   ------------------------------------- -- 34.6/37.3 MB 2.4 MB/s eta 0:00:02
   ------------------------------------- -- 34.9/37.3 MB 2.4 MB/s eta 0:00:02
   ------------------------------------- -- 35.4/37.3 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 35.9/37.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  36.7/37.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 2.4 MB/s  0:00:15
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Load Dataset

In [4]:
df = pd.read_csv(
    "WA_Fn-UseC_-Telco-Customer-Churn.csv"
)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Dataset Information

In [5]:
print("Dataset Shape:")
print(df.shape)


print("\nColumns:")
print(df.columns)


print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape:
(7043, 21)

Columns:
Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

Missing Values:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Check Churn Values

In [6]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

Convert TotalCharges to Numeric

In [7]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

Remove Customer ID

In [8]:
df = df.drop(
    "customerID",
    axis=1
)


df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Separate Features and Target

In [9]:
X = df.drop(
    "Churn",
    axis=1
)


y = df["Churn"]


print(X.shape)

print(y.shape)

(7043, 19)
(7043,)

Train Test Split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.2,

    random_state=42,

    stratify=y

)


print(
    X_train.shape,
    X_test.shape
)

(5634, 19) (1409, 19)

Identify Numerical Features

In [11]:
numeric_features = [

    "SeniorCitizen",

    "tenure",

    "MonthlyCharges",

    "TotalCharges"

]


numeric_features

['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

Identify Categorical Features

In [12]:
categorical_features = [

    col for col in X.columns

    if col not in numeric_features

]


categorical_features

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

Numerical Pipeline

In [13]:
numeric_pipeline = Pipeline(

    steps=[

        (
            "imputer",
            SimpleImputer(
                strategy="median"
            )
        ),

        (
            "scaler",
            StandardScaler()
        )

    ]

)

Categorical Pipeline

In [14]:
categorical_pipeline = Pipeline(

    steps=[

        (
            "imputer",
            SimpleImputer(
                strategy="most_frequent"
            )
        ),


        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )

    ]

)

Column Transformer

In [15]:
preprocessor = ColumnTransformer(

    transformers=[


        (
            "num",
            numeric_pipeline,
            numeric_features
        ),


        (
            "cat",
            categorical_pipeline,
            categorical_features
        )

    ]

)

Final ML Pipeline

In [16]:
model_pipeline = Pipeline(

    steps=[


        (
            "preprocessor",
            preprocessor
        ),


        (
            "model",
            RandomForestClassifier(
                random_state=42
            )
        )

    ]

)


model_pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', RandomForestClassifier(random_state=42))])

Train Model

In [17]:
model_pipeline.fit(

    X_train,

    y_train

)


print(
    "Training Completed"
)

Training Completed

Prediction

In [18]:
y_pred = model_pipeline.predict(

    X_test

)


y_pred[:10]

array(['No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
      dtype=object)

Accuracy

In [19]:
accuracy = accuracy_score(

    y_test,

    y_pred

)


print(
    "Accuracy:",
    accuracy
)

Accuracy: 0.7778566359119943

Confusion Matrix

In [20]:
print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

[[918 117]
 [196 178]]

Classification Report

In [21]:
print(

classification_report(

    y_test,

    y_pred

)

)

              precision    recall  f1-score   support

          No       0.82      0.89      0.85      1035
         Yes       0.60      0.48      0.53       374

    accuracy                           0.78      1409
   macro avg       0.71      0.68      0.69      1409
weighted avg       0.77      0.78      0.77      1409

Save Pipeline

In [22]:
joblib.dump(

    model_pipeline,

    "customer_churn_pipeline.pkl"

)


print(
    "Pipeline Saved"
)

Pipeline Saved

Load Pipeline

In [23]:
loaded_pipeline = joblib.load(

    "customer_churn_pipeline.pkl"

)


print(
    "Pipeline Loaded"
)

Pipeline Loaded

New Customer Prediction

In [24]:
new_customer = pd.DataFrame({

    "gender":["Female"],

    "SeniorCitizen":[0],

    "Partner":["Yes"],

    "Dependents":["No"],

    "tenure":[5],

    "PhoneService":["Yes"],

    "MultipleLines":["No"],

    "InternetService":["Fiber optic"],

    "OnlineSecurity":["No"],

    "OnlineBackup":["Yes"],

    "DeviceProtection":["No"],

    "TechSupport":["No"],

    "StreamingTV":["Yes"],

    "StreamingMovies":["Yes"],

    "Contract":["Month-to-month"],

    "PaperlessBilling":["Yes"],

    "PaymentMethod":["Electronic check"],

    "MonthlyCharges":[850],

    "TotalCharges":[4250]

})


new_customer

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,5,Yes,No,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,850,4250

Predict

In [25]:
prediction = loaded_pipeline.predict(

    new_customer

)


print(
    "Churn Prediction:",
    prediction[0]
)

Churn Prediction: Yes